# Generated by Django 4.1.5 on 2023-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("second_name", models.CharField(max_length=40)),
                ("age", models.CharField(default=18, max_length=3)),
            ],
        ),
    ]
